// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

void initEngine() => AqlossCore.instance.api.crateApiInitEngine();

Future<TrackInfo> loadTrack({required String path}) =>
    AqlossCore.instance.api.crateApiLoadTrack(path: path);

Future<void> play() => AqlossCore.instance.api.crateApiPlay();

Future<void> pause() => AqlossCore.instance.api.crateApiPause();

Future<void> stop() => AqlossCore.instance.api.crateApiStop();

Future<void> seek({required double positionSecs}) =>
    AqlossCore.instance.api.crateApiSeek(positionSecs: positionSecs);

Future<void> setVolume({required double volume}) =>
    AqlossCore.instance.api.crateApiSetVolume(volume: volume);

Future<PlaybackPosition> getPosition() =>
    AqlossCore.instance.api.crateApiGetPosition();

bool isPlaying() => AqlossCore.instance.api.crateApiIsPlaying();

bool isExclusiveMode() => AqlossCore.instance.api.crateApiIsExclusiveMode();

Future<TrackInfo> readMetadata({required String path}) =>
    AqlossCore.instance.api.crateApiReadMetadata(path: path);

Future<Uint8List?> readAlbumArt({required String path}) =>
    AqlossCore.instance.api.crateApiReadAlbumArt(path: path);

Future<List<String>> scanDirectory({required String path}) =>
    AqlossCore.instance.api.crateApiScanDirectory(path: path);

Future<String?> readEmbeddedLyrics({required String path}) =>
    AqlossCore.instance.api.crateApiReadEmbeddedLyrics(path: path);

Future<Float32List> getSpectrumData({required int bucketCount}) =>
    AqlossCore.instance.api.crateApiGetSpectrumData(bucketCount: bucketCount);

/// Update Discord presence while playing.
Future<void> discordUpdatePlaying({
  required String title,
  required String artist,
  required String album,
  required String albumArtUrl,
  required double positionSecs,
  required double durationSecs,
}) => AqlossCore.instance.api.crateApiDiscordUpdatePlaying(
  title: title,
  artist: artist,
  album: album,
  albumArtUrl: albumArtUrl,
  positionSecs: positionSecs,
  durationSecs: durationSecs,
);

Future<void> discordUpdatePaused({
  required String title,
  required String artist,
  required String album,
  required String albumArtUrl,
}) => AqlossCore.instance.api.crateApiDiscordUpdatePaused(
  title: title,
  artist: artist,
  album: album,
  albumArtUrl: albumArtUrl,
);

Future<void> discordClear() => AqlossCore.instance.api.crateApiDiscordClear();
