// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> initEngine() => AqlossCore.instance.api.crateApiInitEngine();

Future<void> initEngineWithDevice({
  required String deviceId,
  required bool exclusive,
}) => AqlossCore.instance.api.crateApiInitEngineWithDevice(
  deviceId: deviceId,
  exclusive: exclusive,
);

Future<void> reinitEngine({
  required String deviceId,
  required bool exclusive,
}) => AqlossCore.instance.api.crateApiReinitEngine(
  deviceId: deviceId,
  exclusive: exclusive,
);

Future<List<AudioDeviceInfo>> enumerateAudioDevices() =>
    AqlossCore.instance.api.crateApiEnumerateAudioDevices();

Future<TrackInfo> loadTrack({required String path}) =>
    AqlossCore.instance.api.crateApiLoadTrack(path: path);

Future<void> play() => AqlossCore.instance.api.crateApiPlay();

Future<void> pause() => AqlossCore.instance.api.crateApiPause();

Future<void> stop() => AqlossCore.instance.api.crateApiStop();

Future<void> seek({required double positionSecs}) =>
    AqlossCore.instance.api.crateApiSeek(positionSecs: positionSecs);

Future<void> setVolume({required double volume}) =>
    AqlossCore.instance.api.crateApiSetVolume(volume: volume);

Future<PlaybackPosition> getPosition() =>
    AqlossCore.instance.api.crateApiGetPosition();

bool isPlaying() => AqlossCore.instance.api.crateApiIsPlaying();

bool isExclusiveMode() => AqlossCore.instance.api.crateApiIsExclusiveMode();

Future<void> setReplayGain({required double linearGain}) =>
    AqlossCore.instance.api.crateApiSetReplayGain(linearGain: linearGain);

Future<void> setSoftClip({required bool enabled}) =>
    AqlossCore.instance.api.crateApiSetSoftClip(enabled: enabled);

Future<void> setSkipSilence({required bool enabled}) =>
    AqlossCore.instance.api.crateApiSetSkipSilence(enabled: enabled);

Future<void> setGapless({required bool enabled}) =>
    AqlossCore.instance.api.crateApiSetGapless(enabled: enabled);

Future<void> setCrossfadeSecs({required double secs}) =>
    AqlossCore.instance.api.crateApiSetCrossfadeSecs(secs: secs);

Future<void> setEqEnabled({required bool enabled}) =>
    AqlossCore.instance.api.crateApiSetEqEnabled(enabled: enabled);

Future<void> setEqGains({required List<double> gains}) =>
    AqlossCore.instance.api.crateApiSetEqGains(gains: gains);

Future<void> setEqBand({required int band, required double gainDb}) =>
    AqlossCore.instance.api.crateApiSetEqBand(band: band, gainDb: gainDb);

Future<Float32List> getEqGains() =>
    AqlossCore.instance.api.crateApiGetEqGains();

Future<Float32List> getSpectrumData({required int bucketCount}) =>
    AqlossCore.instance.api.crateApiGetSpectrumData(bucketCount: bucketCount);

Future<TrackInfo> readMetadata({required String path}) =>
    AqlossCore.instance.api.crateApiReadMetadata(path: path);

Future<Uint8List?> readAlbumArt({required String path}) =>
    AqlossCore.instance.api.crateApiReadAlbumArt(path: path);

Future<List<String>> scanDirectory({required String path}) =>
    AqlossCore.instance.api.crateApiScanDirectory(path: path);

Future<String?> readEmbeddedLyrics({required String path}) =>
    AqlossCore.instance.api.crateApiReadEmbeddedLyrics(path: path);

Future<void> discordUpdatePlaying({
  required String title,
  required String artist,
  required String album,
  required String albumArtUrl,
  required double positionSecs,
  required double durationSecs,
}) => AqlossCore.instance.api.crateApiDiscordUpdatePlaying(
  title: title,
  artist: artist,
  album: album,
  albumArtUrl: albumArtUrl,
  positionSecs: positionSecs,
  durationSecs: durationSecs,
);

Future<void> discordUpdatePaused({
  required String title,
  required String artist,
  required String album,
  required String albumArtUrl,
}) => AqlossCore.instance.api.crateApiDiscordUpdatePaused(
  title: title,
  artist: artist,
  album: album,
  albumArtUrl: albumArtUrl,
);

Future<void> discordClear() => AqlossCore.instance.api.crateApiDiscordClear();

class AudioDeviceInfo {
  final String id;
  final String name;
  final bool isDefault;
  final bool supportsExclusive;

  const AudioDeviceInfo({
    required this.id,
    required this.name,
    required this.isDefault,
    required this.supportsExclusive,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      isDefault.hashCode ^
      supportsExclusive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioDeviceInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          isDefault == other.isDefault &&
          supportsExclusive == other.supportsExclusive;
}
