// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'lib.freezed.dart';

class PlaybackPosition {
  final double positionSecs;
  final double durationSecs;
  final int sampleRate;
  final int bitDepth;

  const PlaybackPosition({
    required this.positionSecs,
    required this.durationSecs,
    required this.sampleRate,
    required this.bitDepth,
  });

  @override
  int get hashCode =>
      positionSecs.hashCode ^
      durationSecs.hashCode ^
      sampleRate.hashCode ^
      bitDepth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaybackPosition &&
          runtimeType == other.runtimeType &&
          positionSecs == other.positionSecs &&
          durationSecs == other.durationSecs &&
          sampleRate == other.sampleRate &&
          bitDepth == other.bitDepth;
}

@freezed
sealed class TrackInfo with _$TrackInfo {
  const factory TrackInfo({
    required String path,
    String? title,
    String? artist,
    String? album,
    String? albumArtist,
    int? trackNumber,
    required double durationSecs,
    required int sampleRate,
    int? bitDepth,
    required int channels,
    required String format,
    required BigInt fileSizeBytes,
  }) = _TrackInfo;
}
